# t
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    name: nginx
    targetPort: 80
    nodePort: 32756
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxcontainer
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curldeployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curlcontainer
        image: radial/busyboxplus:curl
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
