name: testing workflow

on: [push]

jobs:
  example:
    name: setup env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.14.1'
          kubernetes version: 'v1.20.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check kube conf 
        run: cat ~/.kube/config
      - name: Interact with the cluster
        run: kubectl get nodes
      - name: deployment
        run: kubectl apply -f deployment.yml 
      - name: check deployment
        run: kubectl describe deployment nginx-deployment
