name: PR Open

on: [pull_request]

jobs:
  deployment:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: start minikube 
        id: minikube
        uses: medyagh/setup-minikube@master
      - name: deployment
        run: kubectl apply -f deployment.yml 
      - name: kpa
        run: kubectl get pods -A
      - name: check addons
        run: minikube addons list
      - name: wait
        run: while [[ $(kubectl -n default get pods -l app=curl -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done
      - name: test
        run: kubectl exec deploy/curldeployment -- curl -s nginx | grep "Welcome to nginx!"
