name: PR Open

on: [pull_request]

jobs:
  deployment:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: minikube
        uses: opsgang/ga-setup-minikube@v0.1.1
        with:
          minikube-version: 'v1.18.0'
          k8s-version: '1.20.2'
      - name: start minikube
        run: minikube start
      - name: create sa
        run: kubectl create sa default
      - name: deployment
        run: kubectl apply -f deployment.yml 
      - name: wait
        run: while [[ $(kubectl -n kube-system get pods -l k8s-app=kube-dns -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done
      - name: kpa
        run: kubectl get pods -A
      - name: check addons
        run: minikube addons list
      - name: test
        run: kubectl exec deploy/curldeployment -- curl -s nginx | grep "Welcome to nginx!"
